services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "consul agent -dev -client 0.0.0.0"

  kafka-controller-1:
    image: apache/kafka:latest
    container_name: kafka-controller-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /kafka/data/logs
      KAFKA_METADATA_LOG_DIR: /kafka/data/meta
    volumes:
      - ./volumes/kafka_controller_1/logs:/kafka/data/logs
      - ./volumes/kafka_controller_1/meta:/kafka/data/meta

  kafka-controller-2:
    image: apache/kafka:latest
    container_name: kafka-controller-2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /kafka/data/logs
      KAFKA_METADATA_LOG_DIR: /kafka/data/meta
    volumes:
      - ./volumes/kafka_controller_2/logs:/kafka/data/logs
      - ./volumes/kafka_controller_2/meta:/kafka/data/meta

  kafka-controller-3:
    image: apache/kafka:latest
    container_name: kafka-controller-3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /kafka/data/logs
      KAFKA_METADATA_LOG_DIR: /kafka/data/meta
    volumes:
      - ./volumes/kafka_controller_3/logs:/kafka/data/logs
      - ./volumes/kafka_controller_3/meta:/kafka/data/meta

  kafka-broker-1:
    image: apache/kafka:latest
    container_name: kafka-broker-1
    ports:
      - 19092:9092
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /kafka/data/logs
      KAFKA_METADATA_LOG_DIR: /kafka/data/meta
    volumes:
      - ./volumes/kafka_broker_1/logs:/kafka/data/logs
      - ./volumes/kafka_broker_1/meta:/kafka/data/meta
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3

  kafka-broker-2:
    image: apache/kafka:latest
    container_name: kafka-broker-2
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-2:19092,PLAINTEXT_HOST://localhost:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /kafka/data/logs
      KAFKA_METADATA_LOG_DIR: /kafka/data/meta
    volumes:
      - ./volumes/kafka_broker_2/logs:/kafka/data/logs
      - ./volumes/kafka_broker_2/meta:/kafka/data/meta
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3

  kafka-broker-3:
    image: apache/kafka:latest
    container_name: kafka-broker-3
    ports:
      - 39092:9092
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-3:19092,PLAINTEXT_HOST://localhost:49092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /kafka/data/logs
      KAFKA_METADATA_LOG_DIR: /kafka/data/meta
    volumes:
      - ./volumes/kafka_broker_3/logs:/kafka/data/logs
      - ./volumes/kafka_broker_3/meta:/kafka/data/meta
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-broker-1:19092,PLAINTEXT://kafka-broker-2:29092,PLAINTEXT://kafka-broker-3:39092
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_SCHEMA_STORE_DIR=/schema-registry/data
    volumes:
      - ./volumes/schema_registry/data:/schema-registry/data
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    container_name: control-center
    ports:
      - "9021:9021"
    environment:
      - CONTROL_CENTER_BOOTSTRAP_SERVERS=kafka-broker-1:19092,kafka-broker-2:29092,kafka-broker-3:39092
      - CONTROL_CENTER_REST_LISTENERS=http://0.0.0.0:9021
      - CONTROL_CENTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - CONTROL_CENTER_CONTROL=http://schema-registry:8081
      - CONTROL_CENTER_REPLICATION_FACTOR=3
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - schema-registry

  coordinator:
    build:
      context: .
      dockerfile: coordinator/Dockerfile
    ports:
      - "8800:8800"
    environment:
      - CONSUL_ADDR=http://consul:8500
      - SERVICE_HOST=coordinator
      - DEBUG=true
    depends_on:
      - consul

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8000:8080"
    environment:
      - CONSUL_ADDR=http://consul:8500
      - SERVICE_NAME=gateway
      - SERVICE_HOST=127.0.0.1
      - SERVICE_PORT=8080
      - DEBUG=false
    depends_on:
      - consul

  order:
    build:
      context: .
      dockerfile: order/Dockerfile
    ports:
      - "8001:8081"
    environment:
      - CONSUL_ADDR=http://consul:8500
      - SERVICE_NAME=order-service
      - SERVICE_HOST=order
      - SERVICE_PORT=8081
      - DEBUG=false
    depends_on:
      - consul
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

  menu:
    build:
      context: .
      dockerfile: menu/Dockerfile
    ports:
      - "8002:8082"
    environment:
      - CONSUL_ADDR=http://consul:8500
      - SERVICE_NAME=menu-service
      - SERVICE_HOST=menu
      - SERVICE_PORT=8082
      - KAFKA_BROKERS=kafka-broker-1:19092,kafka-broker-2:29092,kafka-broker-3:39092
      - KAFKA_TOPICS=test-topic
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - DEBUG=false
    volumes:
      - ./menu/database/menu.db:/app/menu/database/menu.db
    depends_on:
      - consul
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3

  stock:
    build:
      context: .
      dockerfile: stock/Dockerfile
    ports:
      - "8003:8083"
    environment:
      - CONSUL_ADDR=http://consul:8500
      - SERVICE_NAME=stock-service
      - SERVICE_HOST=stock
      - SERVICE_PORT=8083
      - KAFKA_BROKERS=kafka-broker-1:19092,kafka-broker-2:29092,kafka-broker-3:39092
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - DEBUG=false
    volumes:
      - ./stock/database/stock.db:/app/stock/database/stock.db
    depends_on:
      - consul
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
