// Code generated by avrogen. DO NOT EDIT.

package avro

import (
	"github.com/heetch/avro/avrotypegen"
)

type MenuCreatedEvent struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	UnitPrice int    `json:"unitPrice"`
	Currency  string `json:"currency"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (MenuCreatedEvent) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"id","type":"string"},{"name":"name","type":"string"},{"name":"unitPrice","type":"int"},{"name":"currency","type":"string"}],"name":"example.com.common.api.avro.MenuCreatedEvent","type":"record"}`,
		Required: []bool{
			0: true,
			1: true,
			2: true,
			3: true,
		},
	}
}
